# Generated by Django 4.2 on 2023-05-09 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_cliente_telefono_alter_cliente_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 9, 19, 49, 23, 447939), max_length=15, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_consulta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 9, 19, 49, 23, 447939), max_length=15, verbose_name='Fecha de consulta'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='observaciones',
            field=models.TextField(max_length=500, verbose_name='Observaciones'),
        ),
    ]
